CREATE TABLE "sys_dict_item" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_dict_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"dict_id" bigint NOT NULL,
	"label" varchar(128) NOT NULL,
	"value" varchar(128) NOT NULL,
	"sort" integer DEFAULT 0 NOT NULL,
	"status" smallint DEFAULT 1 NOT NULL,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_dict" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_dict_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"type" varchar(64) NOT NULL CONSTRAINT "uniq_dict_type" UNIQUE,
	"name" varchar(64) NOT NULL,
	"status" smallint DEFAULT 1 NOT NULL,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_file" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_file_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"key" varchar(255) NOT NULL,
	"filename" varchar(255) NOT NULL,
	"size" integer NOT NULL,
	"mime_type" varchar(128),
	"url" varchar(512) NOT NULL,
	"uploader_id" bigint,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_ip_blacklist" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_ip_blacklist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ip" varchar(64) NOT NULL,
	"reason" text,
	"expire_at" timestamp with time zone,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_login_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_login_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint DEFAULT 0 NOT NULL,
	"username" varchar(64) DEFAULT '',
	"ip" varchar(64),
	"ip_region" varchar(64),
	"user_agent" varchar(512),
	"browser" varchar(64) DEFAULT '',
	"os" varchar(64) DEFAULT '',
	"status" varchar(16) NOT NULL,
	"error_msg" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sys_oper_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_oper_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint DEFAULT 0 NOT NULL,
	"username" varchar(64) DEFAULT '',
	"module" varchar(32) NOT NULL,
	"action" varchar(32) NOT NULL,
	"method" varchar(8) NOT NULL,
	"url" varchar(512) NOT NULL,
	"ip" varchar(64),
	"ip_region" varchar(64),
	"user_agent" varchar(512),
	"request_params" jsonb,
	"response_result" jsonb,
	"status" smallint NOT NULL,
	"error_msg" text,
	"cost_ms" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "sys_menu" ADD COLUMN "scope" smallint DEFAULT 1 NOT NULL;--> statement-breakpoint
CREATE INDEX "idx_dict_item_dict_id" ON "sys_dict_item" ("dict_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_dict_item_dict_id_label" ON "sys_dict_item" ("dict_id","label");--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_dict_item_dict_id_value" ON "sys_dict_item" ("dict_id","value");--> statement-breakpoint
CREATE INDEX "idx_dict_type" ON "sys_dict" ("type");--> statement-breakpoint
CREATE INDEX "idx_sys_file_url" ON "sys_file" ("url");--> statement-breakpoint
CREATE INDEX "idx_login_log_user_id" ON "sys_login_log" ("user_id");--> statement-breakpoint
CREATE INDEX "idx_login_log_create_time" ON "sys_login_log" ("created_at");--> statement-breakpoint
CREATE INDEX "idx_oper_log_user_id" ON "sys_oper_log" ("user_id");--> statement-breakpoint
CREATE INDEX "idx_oper_log_create_time" ON "sys_oper_log" ("created_at");--> statement-breakpoint
CREATE INDEX "idx_oper_log_module_action" ON "sys_oper_log" ("module","action");