CREATE TABLE "sys_dept" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_dept_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"code" varchar(100) NOT NULL UNIQUE,
	"parent_id" bigint DEFAULT 0,
	"tree_path" varchar(255) NOT NULL,
	"sort" smallint DEFAULT 0,
	"status" smallint DEFAULT 1,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_menu" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_menu_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"parent_id" bigint DEFAULT 0 NOT NULL,
	"tree_path" varchar(255),
	"type" char(1) NOT NULL,
	"name" varchar(64) NOT NULL,
	"route_name" varchar(255),
	"route_path" varchar(128),
	"component" varchar(128),
	"perm" varchar(128),
	"always_show" smallint DEFAULT 0,
	"keep_alive" smallint DEFAULT 0,
	"visible" smallint DEFAULT 1 NOT NULL,
	"sort" integer DEFAULT 0,
	"icon" varchar(64),
	"redirect" varchar(128),
	"params" jsonb,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_role_dept" (
	"role_id" bigint,
	"dept_id" bigint,
	CONSTRAINT "sys_role_dept_pkey" PRIMARY KEY("role_id","dept_id")
);
--> statement-breakpoint
CREATE TABLE "sys_role_menu" (
	"role_id" bigint,
	"menu_id" bigint,
	CONSTRAINT "sys_role_menu_pkey" PRIMARY KEY("role_id","menu_id")
);
--> statement-breakpoint
CREATE TABLE "sys_user_role" (
	"user_id" bigint,
	"role_id" bigint,
	CONSTRAINT "sys_user_role_pkey" PRIMARY KEY("user_id","role_id")
);
--> statement-breakpoint
CREATE TABLE "sys_role" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(64) NOT NULL UNIQUE,
	"code" varchar(32) NOT NULL UNIQUE,
	"sort" integer DEFAULT 0,
	"status" smallint DEFAULT 1 NOT NULL,
	"data_scope" smallint DEFAULT 1,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_user" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"username" varchar(64) NOT NULL UNIQUE,
	"nickname" varchar(64),
	"gender" smallint DEFAULT 1,
	"password" varchar(100) NOT NULL,
	"dept_id" integer,
	"avatar" varchar(255),
	"mobile" varchar(20),
	"status" smallint DEFAULT 1 NOT NULL,
	"email" varchar(128),
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
