import { pgTable, bigint, varchar, smallint, integer } from "drizzle-orm/pg-core";
import { auditColumns } from "@db/schema/_shared";

/**
 * 系统用户表
 * 参考 youlai-boot 的 sys_user 设计，使用 Drizzle schema 原生定义
 */
export const sysUser = pgTable(
  "sys_user",
  {
    /** 主键 ID，使用 GENERATED BY DEFAULT 支持手动插入种子数据 */
    id: bigint({ mode: "number" }).primaryKey().generatedByDefaultAsIdentity(),
    /** 用户名（唯一索引） */
    username: varchar("username", { length: 64 }).notNull().unique(),
    /** 昵称 */
    nickname: varchar("nickname", { length: 64 }),
    /** 性别（1-男 2-女 0-保密） */
    gender: smallint("gender").default(1),
    /** 密码（bcrypt/argon2 哈希后存储） */
    password: varchar("password", { length: 100 }).notNull(),
    /** 部门 ID，关联 sys_dept */
    deptId: integer("dept_id"),
    /** 用户头像 URL */
    avatar: varchar("avatar", { length: 255 }),
    /** 手机号 */
    mobile: varchar("mobile", { length: 20 }),
    /** 状态（1-正常 0-禁用） */
    status: smallint("status").default(1).notNull(),
    /** 邮箱 */
    email: varchar("email", { length: 128 }),
    /** 审计字段（创建人/创建时间/更新人/更新时间/删除时间） */
    ...auditColumns,
  },
);