CREATE TABLE "sys_config" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_config_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"config_name" varchar(128) NOT NULL,
	"config_key" varchar(128) NOT NULL UNIQUE,
	"config_value" varchar(2000) NOT NULL,
	"remark" varchar(255) DEFAULT '' NOT NULL,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_dept" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_dept_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"code" varchar(100) NOT NULL UNIQUE,
	"parent_id" bigint DEFAULT 0,
	"tree_path" varchar(255) NOT NULL,
	"sort" smallint DEFAULT 0,
	"status" smallint DEFAULT 1,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_dict_item" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_dict_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"dict_id" bigint NOT NULL,
	"label" varchar(128) NOT NULL,
	"value" varchar(128) NOT NULL,
	"sort" integer DEFAULT 0 NOT NULL,
	"status" smallint DEFAULT 1 NOT NULL,
	"tag_type" varchar(8) DEFAULT 'N' NOT NULL,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_dict" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_dict_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"type" varchar(64) NOT NULL CONSTRAINT "uniq_dict_type" UNIQUE,
	"name" varchar(64) NOT NULL,
	"status" smallint DEFAULT 1 NOT NULL,
	"remark" varchar(255) DEFAULT '' NOT NULL,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_file" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_file_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"key" varchar(255) NOT NULL,
	"filename" varchar(255) NOT NULL,
	"size" integer NOT NULL,
	"mime_type" varchar(128),
	"url" varchar(512) NOT NULL,
	"uploader_id" bigint,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_ip_blacklist" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_ip_blacklist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"ip" varchar(64) NOT NULL,
	"reason" text,
	"expire_at" timestamp with time zone,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_login_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_login_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint DEFAULT 0 NOT NULL,
	"username" varchar(64) DEFAULT '',
	"ip" varchar(64),
	"ip_region" varchar(64),
	"user_agent" varchar(512),
	"browser" varchar(64) DEFAULT '',
	"os" varchar(64) DEFAULT '',
	"status" varchar(16) NOT NULL,
	"error_msg" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sys_menu" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_menu_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"parent_id" bigint DEFAULT 0 NOT NULL,
	"tree_path" varchar(255),
	"type" char(1) NOT NULL,
	"name" varchar(64) NOT NULL,
	"route_name" varchar(255),
	"route_path" varchar(128),
	"component" varchar(128),
	"perm" varchar(128),
	"always_show" smallint DEFAULT 0,
	"keep_alive" smallint DEFAULT 0,
	"visible" smallint DEFAULT 1 NOT NULL,
	"sort" integer DEFAULT 0,
	"icon" varchar(64),
	"redirect" varchar(128),
	"params" jsonb,
	"scope" smallint DEFAULT 1 NOT NULL,
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_oper_log" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_oper_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint DEFAULT 0 NOT NULL,
	"username" varchar(64) DEFAULT '',
	"module" varchar(32) NOT NULL,
	"action" varchar(32) NOT NULL,
	"method" varchar(8) NOT NULL,
	"url" varchar(512) NOT NULL,
	"ip" varchar(64),
	"ip_region" varchar(64),
	"user_agent" varchar(512),
	"request_params" jsonb,
	"response_result" jsonb,
	"status" smallint NOT NULL,
	"error_msg" text,
	"cost_ms" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sys_role_dept" (
	"role_id" bigint,
	"dept_id" bigint,
	CONSTRAINT "sys_role_dept_pkey" PRIMARY KEY("role_id","dept_id")
);
--> statement-breakpoint
CREATE TABLE "sys_role_menu" (
	"role_id" bigint,
	"menu_id" bigint,
	CONSTRAINT "sys_role_menu_pkey" PRIMARY KEY("role_id","menu_id")
);
--> statement-breakpoint
CREATE TABLE "sys_user_role" (
	"user_id" bigint,
	"role_id" bigint,
	CONSTRAINT "sys_user_role_pkey" PRIMARY KEY("user_id","role_id")
);
--> statement-breakpoint
CREATE TABLE "sys_role" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(64) NOT NULL UNIQUE,
	"code" varchar(32) NOT NULL UNIQUE,
	"sort" integer DEFAULT 0,
	"status" smallint DEFAULT 1 NOT NULL,
	"data_scope" smallint DEFAULT 1,
	"remark" varchar(255),
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sys_user" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sys_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"username" varchar(64) NOT NULL UNIQUE,
	"nickname" varchar(64),
	"gender" smallint DEFAULT 1,
	"password" varchar(255) NOT NULL,
	"dept_id" integer,
	"avatar" varchar(255),
	"mobile" varchar(20),
	"status" smallint DEFAULT 1 NOT NULL,
	"email" varchar(128),
	"created_by" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" bigint,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "idx_dict_item_dict_id" ON "sys_dict_item" ("dict_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_dict_item_dict_id_label" ON "sys_dict_item" ("dict_id","label");--> statement-breakpoint
CREATE UNIQUE INDEX "uniq_dict_item_dict_id_value" ON "sys_dict_item" ("dict_id","value");--> statement-breakpoint
CREATE INDEX "idx_dict_type" ON "sys_dict" ("type");--> statement-breakpoint
CREATE INDEX "idx_sys_file_url" ON "sys_file" ("url");--> statement-breakpoint
CREATE INDEX "idx_login_log_user_id" ON "sys_login_log" ("user_id");--> statement-breakpoint
CREATE INDEX "idx_login_log_create_time" ON "sys_login_log" ("created_at");--> statement-breakpoint
CREATE INDEX "idx_oper_log_user_id" ON "sys_oper_log" ("user_id");--> statement-breakpoint
CREATE INDEX "idx_oper_log_create_time" ON "sys_oper_log" ("created_at");--> statement-breakpoint
CREATE INDEX "idx_oper_log_module_action" ON "sys_oper_log" ("module","action");